new_urls:
  - ".amazonaws.com"
  - ".vficloud.net"
  - ".prodvficloud.net"
  - ".verifone.cloud"
  - ".redhat.com"
  - ".verifone.com"
  - ".elastic.co"
  - ".cardinalcommerce.com"
  - ".okta.com"
  - ".mtls.okta.com"
  - ".oktapreview.com"
  - ".mtls.oktapreview.com"
  - ".oktacdn.com"
  - ".okta-emea.com"
  - ".mtls.okta-emea.com"
  - ".kerberos.okta.com"
  - ".kerberos.okta-emea.com"
  - ".kerberos.oktapreview.com"
  - ".digicert.com"
  - ".saas.appdynamics.com"
  - ".scaleft.com"
  - ".app.scaleft.com"
  - "rhui3.us-east-1.aws.ce.redhat.com"
  - ".repo.zabbix.com"
  - ".cloud.wazuh.com"
  - ".sts.amazonaws.com"
  - ".email-smtp.us-east-1.amazonaws.com"
  - "uscst.vam.vficloud.net"
  - "uscst-gb.portal.gsc.vficloud.net"
  - "rhui3.us-east-2.aws.ce.redhat.com"
  - "rhui3.eu-west-2.aws.ce.redhat.com"
  - "uscst.3ds.vficloud.net"
  - "uscst.checkout.vficloud.net"
  - "uscst-gb.gsc.vficloud.net"
  - ".snowflakecomputing.com"
  - ".amazontrust.com"
  - "o.ss2.us"
  - ".digicert.com"
  - ".starfieldtech.com"
  - "duo.com"
  - ".openam-verifone-usw2-staging.id.forgerock.io"
  - ".mapi.alipaydev.com"
  - ".sftp.alipay.com"
  - ".itdm-certif.desjardins.com"
  - ".api.mch.weixin.qq.com"
  - ".api.playground.klarna.com"
  - ".auth-bp.klarna.com"
  - ".api-na.playground.klarna.com"
  - ".api.sandbox.paypal.com"
  - ".reports.sandbox.paypal.com"
  - ".uscst.test.vficloud.net"
  - ".staging1.verifonehq.net/apis/v1.1/ping"
  - ".staging1.verifonehq.net"
  - ".staging1.verifonehq.net/MessagingServer/MessageHandler.asmx"
  - ".globalmapi.alipay.com"
  - ".nginx.org"
  - ".downloads.mongodb.com"
  - ".artifacts.elastic.co"
  - ".duosecurity.com"
  - "redislabs.com"
  - ".elb.amazonaws.com"
  - "bitbucket.verifone.cloud"
  - ".google.com/recaptcha/api/siteverify"
  - ".api.paypal.com"
  - ".reports.paypal.com"
  - ".centineltest.cardinalcommerce.com/maps/txns.asp"
