---
- name: Install Squid and start service
  ansible.builtin.dnf:
    name: squid
    state: latest

- name: Copy squid.conf
  template:
    src: templates/squid.conf.j2
    dest: /etc/squid/squid.conf
    mode: '0644'
  notify: restart squid

- name: Start and enable Squid service
  ansible.builtin.systemd:
    name: squid
    state: started
    enabled: true
